name: "Mark new issues with needs-triage label"

on:
  issues:
    types:
      - reopened
      - opened

permissions:
  # Label issues.
  issues: write

jobs:
  label-new-issues:
    runs-on: ubuntu-latest
    steps:
      - name: initial labelling
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            if (!context.payload.issue.assignee) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['needs triage'],
              });
            }
